name: Deploying
on: 
    workflow_call: 
        inputs:
            sufix:
                required: true
                type: string
            prefix:
                required: true
                type: string
            files:
                required: true
                type: string
            path:
                required: true
                type: string
            env:
                required: true
                type: string
            image: 
                required: true
                type: string
        secrets:
            K8S_CONFIG:
                required: true

jobs:
    deploy-call:
        continue-on-error: true
        environment: 
            name: ${{ inputs.env }}
        runs-on: [k8s]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - uses: cschleiden/replace-tokens@v1
              with:
                files: '${{ inputs.files }}'
                tokenPrefix: '${{ inputs.prefix }}'
                tokenSuffix: '${{ inputs.sufix }}'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                IMAGE: ${{ inputs.image }}
                REPLICAS: ${{ vars.REPLICAS }}

            - uses: azure/setup-kubectl@v4
              name: Installing kubectl

            - uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: '${{ secrets.K8S_CONFIG }}'
                context: devops-admin

            - name: Deploying
              shell: pwsh
              run: |
               kubectl get pods 
               cat kubernetes/development/deployment.yaml #kubectl apply -f ${{ inputs.PATH }}

            

            